<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita0d7c3918586f602e431f07da7405e1d
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Picqer\\Barcode\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Picqer\\Barcode\\' => 
        array (
            0 => __DIR__ . '/..' . '/picqer/php-barcode-generator/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita0d7c3918586f602e431f07da7405e1d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita0d7c3918586f602e431f07da7405e1d::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
